GET http://localhost:3000/v1

### get all students
GET http://localhost:3000/v1/students

### get students details
GET http://localhost:3000/v1/students/4

### create students
POST http://localhost:3000/v1/students
Content-Type: application/json

{
    "name":"sogol",
    "age":21,
    "address":"surabaya",
    "is_active":"true"
}

### update
PUT http://localhost:3000/v1/students/5
Content-Type: application/json

{
    "name":"adit",
    "age":21,
    "address":"malang",
    "is_active":"true"
}

### delete
delete http://localhost:3000/v1/students/1